[[plugins]]
repo = 'rhysd/committia.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  set signcolumn=yes
  let g:gitgutter_max_signs = 500
  highlight clear SignColumn
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  nnoremap [fugitive] <Nop>
  nmap <Leader>g [fugitive]

  nnoremap <silent> [fugitive]s  :Gstatus<CR>
  nnoremap <silent> [fugitive]b  :Gblame<CR>
  nnoremap <silent> [fugitive]ca :Gcommit --ammend<CR>
  nnoremap <silent> [fugitive]c  :Gcommit -v -q<CR>
  nnoremap <silent> [fugitive]d  :Gdiff<CR>
  nnoremap <silent> [fugitive]a  :Gwrite<CR>
  nnoremap <silent> [fugitive]r  :Gread<CR>
  nnoremap <silent> [fugitive]p  :Gpush<CR>
  nnoremap <silent> [fugitive]l  :Glog -- %<CR>
'''

[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'idanarye/vim-merginal'

