[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_echo_msg_error_str = 'E'
  let g:ale_echo_msg_warning_str = 'W'
  let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
  let g:ale_set_loclist = 0
  let g:ale_set_quickfix = 1
  let g:ale_open_list = 0
  let g:ale_keep_list_window_open = 0
'''

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'vim-scripts/tComment'

[[plugins]]
repo = 'hashivim/vim-terraform'

[[plugins]]
repo = 'mtscout6/vim-cjsx'
on_ft = ['jsx']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'kana/vim-filetype-haskell'
on_ft = ['haskell']

[[plugins]]
repo = 'elixir-lang/vim-elixir'
on_ft = ['elixir']

[[plugins]]
repo = 'slashmili/alchemist.vim'
on_ft = ['elixir']

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-bundler'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']
hook_add = '''
  nnoremap [vim-rails] <Nop>
  nmap <Leader>r [vim-rails]

  nnoremap <silent> [vim-rails]a :AV<CR>
  nnoremap <silent> [vim-rails]r :RV<CR>
'''

[[plugins]]
repo = 'tpope/vim-apathy'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'jparise/vim-graphql'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'chemzqm/vim-jsx-improve'

[[plugins]]
repo = 'janko-m/vim-test'
depends = ['kassio/neoterm']
hook_add = '''
  let test#strategy = 'neovim'
  let test#ruby#rspec#executable = 'bundle exec rspec'
  let g:test#preserve_screen = 1

  nnoremap [vim-test] <Nop>
  nmap <Leader>t [vim-test]

  nnoremap <silent> [vim-test]t :TestNearest<CR>
  nnoremap <silent> [vim-test]T :TestFile<CR>
  nnoremap <silent> [vim-test]a :TestSuite<CR>
  nnoremap <silent> [vim-test]l :TestLast<CR>
  nnoremap <silent> [vim-test]g :TestVisit<CR>
'''

[[plugins]]
repo = 'vim-erlang/vim-rebar'
on_ft = 'erlang'

[[plugins]]
repo = 'vim-erlang/vim-erlang-runtime'
on_ft = 'erlang'

[[plugins]]
repo = 'vim-erlang/vim-erlang-compiler'
on_ft = 'erlang'

[[plugins]]
repo = 'vim-erlang/vim-erlang-tags'
on_ft = 'erlang'

[[plugins]]
repo = 'vim-erlang/vim-dialyzer'
on_ft = 'erlang'
