[[plugins]]
repo = 'christoomey/vim-run-interactive'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hook_post_source = '''
  let g:ctrlp_use_caching = 0
'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'janko-m/vim-test'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]]
repo = 'pbrisbin/vim-mkdir'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

[[plugins]]
repo = 'tpope/vim-bundler'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-projectionist'

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rake'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'vim-scripts/tComment'

[[plugins]]
repo = 'bogado/file-line'

[[plugins]]
repo = 'junegunn/fzf'
build = '~/.fzf/install --all'
rtp = ''

[[plugins]]
repo = 'kana/vim-smartinput'

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 's3rvac/AutoFenc'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = ['/deoplete-ruby']

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo =  'Shougo/vimproc'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'tpope/vim-abolish'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'mhartington/oceanic-next'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'cohama/agit.vim'

[[plugins]]
repo = 'rhysd/committia.vim'

[[plugins]]
repo = 'idanarye/vim-merginal'

[[plugins]]
repo = 'kana/vim-filetype-haskell'
on_ft = ['haskell']

[[plugins]]
repo = 'elixir-lang/vim-elixir'
on_ft = ['elixir']

[[plugins]]
repo = 'slashmili/alchemist.vim'

[[plugins]]
repo = 'kovisoft/slimv'
on_ft = ['lisp']

[[plugins]]
repo = 'mtscout6/vim-cjsx'
on_ft = ['jsx']

[[plugins]]
repo = 'stephpy/vim-php-cs-fixer'
on_ft = ['php']

[[plugins]]
repo = 'vim-php/vim-composer'
on_ft = ['php']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'rust-lang/rust.vim'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'jparise/vim-graphql'

[[plugins]]
repo = 'kannokanno/previm'
hook_post_source = '''
  let g:previm_open_cmd = 'open'
'''

[[plugins]]
repo = 'pmsorhaindo/syntastic-local-eslint.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'chemzqm/vim-jsx-improve'

[[plugins]]
repo = 'scrooloose/nerdtree'
